postgres:
  adapter: postgresql
  database: active_record_temptable_test
  user: postgres
sqlite:
  adapter: sqlite3
  database: ":memory:"
mysql:
  adapter: mysql2
  database: active_record_temptable_test